### PR TITLE
Attach event listeners directly to isolated boundaries

### PR DESCRIPTION
**Pull request by TylorS**
Possible solution to cyclejs/core#229

### CODE REVIEW

**Comment by TylorS** [comment]
cc @laszlokorte

**Comment by staltz** [comment]
Hmm, this is tricky because it goes back to attaching event listeners on non-root elements, which may pose as a perf problem if isolated components are created/recreated often. I agree that the processing order should be from innermost to outermost, but can't we solve that in a different way?

**Comment by TylorS** [comment]
Very good point, maybe we should sit on this a while and think a bit more.

**Comment by laszlokorte** [comment]
Would recreation of an component really lead to reattachment of the listener?

Say I have a component with scope `foo`. The root element of this component is a div.
This div will be marked as scope `foo`. First time the component is mounted, this div would be put into the map of boundary element.

Now even if the component is recreated I would assume that the vtree diff leads to the root of that component being the same "real" div as before. So there wont be any insertion or deletion. There would not happen any reattachment of the listeners. Maybe I am missing something. I will take a closer look at the implementation later.

**Comment by staltz** [comment]
We just implemented this (Tylor and I, pair programming) on the Diversity branch. :+1:

**Pull request closed without merging**
