### PR TITLE
dom issue 222 WIP

### PR DESCRIPTION
**Pull request by Cmdv**

### CODE REVIEW

**Comment by staltz** [comment]
@Cmdv in order for this issue to be properly solved, we need to get at least TypeScript compiling. `readystate` doesn't exist anywhere. `readyState` does. But only on `Document`, so you need to cast the target to `Document`. See https://github.com/cloud9ide/typescript/blob/master/typings/lib.d.ts#L11087. Then, we also need tests that ensure that the DOM Driver starts only after that ready State event.

**Comment by Cmdv** [comment]
@staltz cool I'll make that amend, first time I've touched TS so got scared! but once I get TS being nice then next step was to add a test. 😄

**Comment by Cmdv** [comment]
@staltz not able to create a test as DOM seems to always be complete when using testem, tried:

```
function createDelayedRenderTarget (id = null) {
  let element = document.createElement('div');
  element.className = 'cycletest';
  if (id) {
    element.id = id;
  }
  setTimeout(() => {
    document.body.appendChild(element);
  }, 400)
  return element;
}

it('should wait for Document to be fully loaded before returning makeDOMDriver', function (done) {
    function app() {
      return {
        DOM: Rx.Observable.of(
          div('.my-render-only-container', [
            h2('Cycle.js framework')
          ])
        )
      };
    }

    const {sinks, sources, run} = Cycle(app, {
      DOM: makeDOMDriver(createDelayedRenderTarget())
    });

    let dispose;
    sources.DOM.select(':root').elements.skip(1).take(1).subscribe(function (root) {
      assert.notStrictEqual(document.readyState, 'complete');
      setTimeout(() => {
        dispose();
        done();
      });
    });
    dispose = run();
  });
```

**Comment by Cmdv** [comment]
Well think I have the solution but I'm unable to get a decent test with Mocha and Testem. Any tips would be great full otherwise I'll just leave this here until someone can come up with a good solution.

**Comment by staltz** [comment]
@Cmdv can you coordinate with @whitecolor ?

**Comment by Cmdv** [comment]
I'll try take a look this evening @staltz

**Comment by Cmdv** [comment]
@staltz @whitecolor this looks like the right implementation but I don't know how to test it. Have tried multiple methods but no joy!

**Comment by Cmdv** [comment]
was this fixed @staltz ?

**Comment by staltz** [comment]
No it wasn't fixed. I didn't close this issue. It was automatically closed because the diversity branch was deleted

**Comment by Cmdv** [comment]
Ah cool @staltz, thought someone had worked it out.

**Pull request closed without merging**
